### PR TITLE
Change HTML5  to HTML

### PR DESCRIPTION
**Pull request by mrhappyma**
Sadly have to get rid of the icon (there's no icon for HTML)

### CODE REVIEW

**Comment by mrhappyma** [comment]
The comit [Change HTML to HTML5](https://github.com/mistertech123/mistertech123/pull/1/commits/61000553e37e69c0c2234798b381418e2a82f8f4) was named incorrectly by accident, it is indeed the opposite (Change HTML5 to HTML).

**Comment by mrhappyma** [comment]
@mistertech123

**Comment by mrhappyma** [comment]
@mistertech123

**Comment by mistertech123** [comment]
Sorry, I already fixed it

**Comment by mrhappyma** [comment]
@mistertech123 doesn't look like it

**Comment by mrhappyma** [comment]
Seems you did this without merging my pull request so no my profile picture next to contributors :(
Closing this pull request

**Comment by mistertech123** [comment]
Correct.

>

**Pull request closed without merging**
